site_name: My Docs

theme:
  name: material
  palette:
    scheme: slate  # 深色主題
    primary: indigo  # 主色
    accent: pink  # 強調色
  font:
    text: Roboto  # 主要字體
    code: Fira Code  # 程式碼字體
    features: []  # 禁用所有預設功能
