site_name: OSSINT

theme:
  name: material
  features:
    - navigation.sections

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html