name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Build and Deploy MkDocs site
        if: github.ref == 'refs/heads/main'
        run: |
          mkdocs gh-deploy --force --clean --verbose